-- Migration: Initial Schema Baseline for AquaGuest
-- Description: Creates the core domain tables, constraints, indexes, and RLS policies.

-- 1. Customers
CREATE TABLE IF NOT EXISTS public.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text,
  address text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 2. Washing Machines
CREATE TABLE IF NOT EXISTS public.washing_machines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  kg numeric NOT NULL DEFAULT 0,
  brand text,
  status text NOT NULL DEFAULT 'available',
  is_available boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 3. Washer Rentals
CREATE TABLE IF NOT EXISTS public.washer_rentals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL,
  customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  machine_id integer,
  shift text,
  delivery_time text,
  pickup_time text,
  pickup_date text,
  delivery_fee numeric NOT NULL DEFAULT 0,
  total_usd numeric NOT NULL DEFAULT 0,
  payment_method text,
  status text NOT NULL DEFAULT 'active',
  date_paid text,
  notes text,
  is_paid boolean NOT NULL DEFAULT false,
  agenda_template_send_state text NOT NULL DEFAULT 'not_sent' CHECK (agenda_template_send_state IN ('not_sent', 'sending', 'sent')),
  agenda_template_sent boolean NOT NULL DEFAULT false,
  agenda_template_sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 4. Sales
CREATE TABLE IF NOT EXISTS public.sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  daily_number integer NOT NULL,
  date text NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  payment_method text,
  total_bs numeric NOT NULL DEFAULT 0,
  total_usd numeric NOT NULL DEFAULT 0,
  exchange_rate numeric NOT NULL DEFAULT 0,
  notes text,
  temp_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 5. Products
CREATE TABLE IF NOT EXISTS public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  default_price numeric NOT NULL DEFAULT 0,
  min_liters numeric,
  max_liters numeric,
  requires_liters boolean NOT NULL DEFAULT false,
  icon text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 6. Expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  category text,
  payment_method text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 7. Prepaid Orders
CREATE TABLE IF NOT EXISTS public.prepaid_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name text NOT NULL,
  customer_phone text,
  liters numeric NOT NULL DEFAULT 0,
  payment_method text,
  date_paid text,
  date_delivered text,
  notes text,
  amount_bs numeric NOT NULL DEFAULT 0,
  amount_usd numeric NOT NULL DEFAULT 0,
  exchange_rate numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 8. Liter Pricing
CREATE TABLE IF NOT EXISTS public.liter_pricing (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  breakpoint numeric NOT NULL,
  price numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 9. Exchange Rates
CREATE TABLE IF NOT EXISTS public.exchange_rates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL UNIQUE,
  rate numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 10. Payment Balance Transactions
CREATE TABLE IF NOT EXISTS public.payment_balance_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL,
  from_method text NOT NULL,
  to_method text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  amount_bs numeric,
  amount_usd numeric,
  amount_out_bs numeric,
  amount_in_bs numeric,
  difference_bs numeric,
  notes text,
  operation_type text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- 11. Sale Payment Splits
CREATE TABLE IF NOT EXISTS public.sale_payment_splits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  payment_method text NOT NULL CHECK (payment_method IN ('efectivo', 'pago_movil', 'punto_venta', 'divisa')),
  amount_bs numeric(12,2) NOT NULL CHECK (amount_bs >= 0),
  amount_usd numeric(12,2) CHECK (amount_usd IS NULL OR amount_usd >= 0),
  exchange_rate_used numeric(12,4) CHECK (exchange_rate_used IS NULL OR exchange_rate_used > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 12. Rental Payment Splits
CREATE TABLE IF NOT EXISTS public.rental_payment_splits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rental_id uuid NOT NULL REFERENCES public.washer_rentals(id) ON DELETE CASCADE,
  payment_method text NOT NULL CHECK (payment_method IN ('efectivo', 'pago_movil', 'punto_venta', 'divisa')),
  amount_bs numeric(12,2) NOT NULL CHECK (amount_bs >= 0),
  amount_usd numeric(12,2) CHECK (amount_usd IS NULL OR amount_usd >= 0),
  exchange_rate_used numeric(12,4) CHECK (exchange_rate_used IS NULL OR exchange_rate_used > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 13. Expense Payment Splits
CREATE TABLE IF NOT EXISTS public.expense_payment_splits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  expense_id uuid NOT NULL REFERENCES public.expenses(id) ON DELETE CASCADE,
  payment_method text NOT NULL CHECK (payment_method IN ('efectivo', 'pago_movil', 'punto_venta', 'divisa')),
  amount_bs numeric(12,2) NOT NULL CHECK (amount_bs >= 0),
  amount_usd numeric(12,2) CHECK (amount_usd IS NULL OR amount_usd >= 0),
  exchange_rate_used numeric(12,4) CHECK (exchange_rate_used IS NULL OR exchange_rate_used > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 14. Tips
CREATE TABLE IF NOT EXISTS public.tips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  origin_type text NOT NULL CHECK (origin_type IN ('sale', 'rental')),
  origin_id uuid NOT NULL,
  tip_date text NOT NULL,
  amount_bs numeric NOT NULL DEFAULT 0 CHECK (amount_bs >= 0),
  amount_usd numeric CHECK (amount_usd IS NULL OR amount_usd >= 0),
  exchange_rate_used numeric CHECK (exchange_rate_used IS NULL OR exchange_rate_used > 0),
  capture_payment_method text NOT NULL CHECK (capture_payment_method IN ('efectivo', 'pago_movil', 'punto_venta', 'divisa')),
  paid_payment_method text CHECK (paid_payment_method IS NULL OR paid_payment_method IN ('efectivo', 'pago_movil', 'punto_venta', 'divisa')),
  paid_at timestamptz,
  notes text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_tips_origin UNIQUE (origin_type, origin_id)
);

-- 15. Tip Payout Idempotency
CREATE TABLE IF NOT EXISTS public.tip_payout_idempotency (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key text NOT NULL UNIQUE,
  scope text NOT NULL CHECK (scope IN ('single', 'day')),
  payment_method text NOT NULL CHECK (payment_method IN ('efectivo', 'pago_movil', 'punto_venta', 'divisa')),
  tip_id uuid,
  tip_date text,
  paid_count integer,
  total_amount_bs numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes for Foreign Keys and Common Query Patterns
CREATE INDEX IF NOT EXISTS idx_washer_rentals_customer_id ON public.washer_rentals (customer_id);
CREATE INDEX IF NOT EXISTS idx_washer_rentals_date ON public.washer_rentals (date);
CREATE INDEX IF NOT EXISTS idx_sales_date ON public.sales (date);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses (date);
CREATE INDEX IF NOT EXISTS idx_tips_tip_date ON public.tips (tip_date);
CREATE INDEX IF NOT EXISTS idx_sale_payment_splits_sale_id ON public.sale_payment_splits (sale_id);
CREATE INDEX IF NOT EXISTS idx_rental_payment_splits_rental_id ON public.rental_payment_splits (rental_id);
CREATE INDEX IF NOT EXISTS idx_expense_payment_splits_expense_id ON public.expense_payment_splits (expense_id);

-- Row Level Security (RLS)
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.washing_machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.washer_rentals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prepaid_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liter_pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exchange_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_balance_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_payment_splits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_payment_splits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_payment_splits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tip_payout_idempotency ENABLE ROW LEVEL SECURITY;

-- Permissive RLS Policies for local development & client access
CREATE POLICY "Allow all on customers" ON public.customers FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on washing_machines" ON public.washing_machines FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on washer_rentals" ON public.washer_rentals FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on sales" ON public.sales FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on products" ON public.products FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on expenses" ON public.expenses FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on prepaid_orders" ON public.prepaid_orders FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on liter_pricing" ON public.liter_pricing FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on exchange_rates" ON public.exchange_rates FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on payment_balance_transactions" ON public.payment_balance_transactions FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on sale_payment_splits" ON public.sale_payment_splits FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on rental_payment_splits" ON public.rental_payment_splits FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on expense_payment_splits" ON public.expense_payment_splits FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on tips" ON public.tips FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on tip_payout_idempotency" ON public.tip_payout_idempotency FOR ALL TO public USING (true) WITH CHECK (true);
